name: "CI tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    if: ${{ github.repository == 'dazuma/toys-test' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "2.7"
            tool: ci
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run ${{ matrix.tool || 'test' }}
        shell: bash
        run: |
          unset JAVA_TOOL_OPTIONS
          ./toys-dev do ci init , "${{ matrix.tool || 'test' }}" < /dev/null
